### ISSUE TITLE
[FIX] - Possível solução para o desafio media do aluno

### ISSUE THREAD

**Issue by luan0ap** [LumusCode/Javascript-completo-2018-do-iniciante-ao-mestre#1]
Aqui uma possível solução para o problema

```
function CalcularMedia(){
        var total = 0
        var quantidade = arguments.length
        var x = 0

        while(typeof arguments[x] === 'number'){
            total += arguments[x]
            x++
        }
        return total / quantidade
    }

CalcularMedia.apply(this, $0.value.split(' ').map(n => parseInt(n)))
```

O $0 é um recurso do chrome, equivale a um elemento do DOM

**Comment by luan0ap** [comment]
No caso ele vai pegar cada valor digitado no input que foi separado

'10 20 40' -> ele vai transformar em ['10', '20', '40']

não sei se você estudou sobre apply, mas ele permite passar um array como N parametros para a sua função

**Comment by luan0ap** [comment]
Básicamente é assim

O `$0` seria seu input o elemento do DOM em si, em seguida pegamos o seu valor com o `value`, até ai acho que deve ta tudo OK.

No `split` nós estamos separando as string do `value` e colocando elas em um array, por exemplo ele vai pegar todo numero que estiver entre espaços pois no `split(' ')` definimos isso . Ou seja, se tivermos umas string com: `'12 34 3434 44'` o resultado será `['12', '34', '3434', '44']`

No `map` nos iteramos cada item desse array e o convertemos em `inteiro`.

Tudo isso é passado para a função através do `apply`  que além de mudar o `this` da função nos permite passar parametros com base em um array. Por exemplo:

`funcao.apply( this, [ 'arg1', 'arg2', 'arg3' ] )`, equivale a isso: `funcao( 'arg1', 'arg2', 'arg3')`

**Comment by LumusCode** [comment]
Saquei, mas onde teria que definir o $0, porque se eu por em uma variável da um Uncaught ReferenceError: $0 is not defined

**Comment by luan0ap** [comment]
Esse $0 seria seu input porém eu utilizei de um recurso do chrome.

Para você entender melhor, abra seu debugger do Chrome (aperte F12), vá na aba `Elementos` e clique em qualquer elemento deixando ele selecionado, agora vá para a aba `Console` e digite `$0`, você vai ver que o resultado será o elemento que foi selecionado na aba `Elementos`. Então no caso isso seria se elemento input.

**Comment by LumusCode** [comment]
Saquei
